name: Build and Deploy Multi

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Build environment'
        required: true
        default: staging
        type: choice
        options:
          - staging
          - dev

concurrency:
  group: ${{ github.workflow }}-${{ inputs.env }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  docker-build-multi:
    uses: strongsdcom/github-actions/.github/workflows/aws-docker-build.yaml@main
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      build-args: |
        SENTRY_ENVIRONMENT=${{ inputs.env }}
        SENTRY_DSN=${{ vars.SENTRY_DSN }}
    with:
      aws-account: ${{ vars.AWS_ACCOUNT }}
      ecr-name: strongsdcom/app-${{ inputs.env }}
  
  deploy-multi:
    uses: strongsdcom/github-actions/.github/workflows/aws-eks-deploy.yaml@main
    needs: docker-build-multi
    environment:
      name: ${{ inputs.env }}
      url: ${{ (inputs.env == 'staging' && vars.ENVIRONMENT_URL_STAGING) || (inputs.env == 'dev' && vars.ENVIRONMENT_URL_DEV) }}
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
    with:
      aws-account: ${{ vars.AWS_ACCOUNT }}
      release-name: ${{ vars.HELM_RELEASE_NAME }}
      helm-set-values: |
        a=1
        b=2
      helm-values: |
        ./.deploy/values/${{ inputs.env }}/config.yaml
        ./.deploy/values/${{ inputs.env }}/secrets.yaml
      namespace: ${{ inputs.env }}
      cluster-name: ${{ vars.K8S_CLUSTER_NAME_ERP_MULTI }}
      image-tag: ${{ needs.docker-build-multi.outputs.image-tag }}
      image-repository: ${{ needs.docker-build-multi.outputs.image-repository }}

  sentry-release:
    runs-on: ubuntu-latest
    uses: strongsdcom/github-actions/.github/workflows/sentry-release.yaml@main
    needs: deploy-multi
    with:
      ignore-empty: true
      release-name: ${{ needs.deploy-multi.outputs.release-name }}
      release-env: ${{ inputs.env }}
      organization: ${{ env.SENTRY_ORG }}
      project: ${{ env.SENTRY_PROJECT }}
      set-commits: skip
    secrets:
      auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
