# Important!
# By default Release Please uses secrets.GITHUB_TOKEN which does not fire published release event
# Use this example only with passed custom token to release-please workflow

name: Jira Release

on:
  release:
    types:
      - published

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  jira-release:
    uses: strongsdcom/github-actions/.github/workflows/jira-release.yaml@main
    secrets:
      email: ${{ secrets.JIRA_EMAIL }}
      token: ${{ secrets.JIRA_TOKEN }}
    with:
      project-key: 'SRE'
      sub-domain: 'hyphe'
      release-name: ${{ github.event.release.tag_name }}
