name: Release Please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    uses: strongsdcom/github-actions/.github/workflows/release-please.yaml@main
    secrets:
      github-token: ${{ secrets.MY_CUSTOM_TOKEN }} # is required only for separate jira release file
    with:
      release-type: elixir
      extra-files: |
        .deploy/Chart.yaml
        apps/b4c_trade/mix.exs
