name: Release

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    uses: bit4coinBV/github-actions/.github/workflows/release-please.yaml@main
  jira-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    uses: bit4coinBV/github-actions/.github/workflows/jira-release.yaml@main
    secrets:
      email: ${{ secrets.JIRA_EMAIL }}
      token: ${{ secrets.JIRA_TOKEN }}
    with:
      project-key: 'SRE'
      sub-domain: 'hyphe'
      release-name: ${{ needs.release-please.outputs.tag-name }}
