on:
  workflow_call:
    secrets:
      aws-access-key-id: 
        required: true
      aws-secret-access-key:
        required: true
      build-args:
        required: false

    inputs:
      tags:
        required: false
        type: string
        default: '<<short-sha>>'
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
      env-name:
        required: false
        type: string
        default: ''
      env-url:
        required: false
        type: string
        default: ''

    outputs:
      image-tag:
        description: "Main Docker Image tag name"
        value: ${{ jobs.docker-build.outputs.image-tag }}
      registry:
        description: "Container Registry (ECR)"
        value: ${{ jobs.docker-build.outputs.registry }}
      repository:
        description: "Docker Image Repository"
        value: ${{ jobs.docker-build.outputs.repository }}
      short-sha:
        description: "Git commit short sha"
        value: ${{ jobs.docker-build.outputs.short-sha }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ inputs.registry }}
      repository: ${{ inputs.repository }}
      image-tag: ${{ steps.get-first-tag.outputs.image-tag }}
      short-sha: ${{ steps.build-short-sha.outputs.short-sha }}
    environment:
      name: ${{ inputs.env-name }}
      url: ${{ inputs.env-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build git commit short sha
        id: build-short-sha
        run: echo "short-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.aws-access-key-id }}
          password: ${{ secrets.aws-secret-access-key }}
      - name: Build Tags
        id: build-tags
        run: |       
          tags=$(echo '${{ inputs.tags }}' | awk '{$1=$1};1' | sed '/^$/d' | sed 's/<<short-sha>>/${{ steps.build-short-sha.outputs.short-sha }}/')
          echo "tags=$tags" >> $GITHUB_OUTPUT
      - name: Get first tag
        id: get-first-tag
        run: |
          image_tag=$(echo '${{ steps.build-tags.outputs.tags }}' | head -1)
          echo "image-tag=$image_tag" >> $GITHUB_OUTPUT
      - name: Build ECR tags
        id: build-ecr-tags
        run: |
          ecr_tags=$(echo '${{ steps.build-tags.outputs.tags }}' | sed 's#.*#${{ inputs.registry }}/${{ inputs.repository }}:&#')
          echo "ecr-tags=$ecr_tags" >> $GITHUB_OUTPUT
      - name: Build Docker Args
        id: build-docker-build-args
        run: |
          docker_build_args=$(echo '${{ secrets.build-args }}' | sed '/^$/d' | sed 's/<<short-sha>>/${{ steps.build-short-sha.outputs.short-sha }}/g')
          echo "build-args=$docker_build_args" >> $GITHUB_OUTPUT
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ${{ steps.build-docker-build-args.outputs.build-args }}
          push: true
          tags: ${{ steps.build-ecr-tags.outputs.ecr-tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
