on:
  workflow_call:
    secrets:
      aws-access-key-id: 
        required: true
      aws-secret-access-key:
        required: true
      build-args:
        required: false

    inputs:
      tags:
        required: false
        type: string
        default: ''
      aws-account:
        required: true
        type: string
      aws-region: 
        required: false
        type: string
        default: 'eu-north-1'
      ecr-name:
        required: true
        type: string
      env-name:
        required: false
        type: string
        default: ''
      env-url:
        required: false
        type: string
        default: ''

    outputs:
      image-tag:
        description: "Docker Image tag name"
        value: ${{ jobs.docker-build.outputs.image-tag }}
      image-repository:
        description: "Docker Image Repository"
        value: ${{ jobs.docker-build.outputs.image-repository }}
      short-sha:
        description: "Git commit short sha"
        value: ${{ jobs.docker-build.outputs.short-sha }}

env:
  REGISTRY: ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      image-repository: ${{ env.REGISTRY }}
      image-tag: ${{ steps.build-tags.outputs.tags }}
      short-sha: ${{ steps.build-short-sha.outputs.short-sha }}
    environment:
      name: ${{ inputs.env-name }}
      url: ${{ inputs.env-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build git commit short sha
        id: build-short-sha
        run: echo "short-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.aws-access-key-id }}
          password: ${{ secrets.aws-secret-access-key }}
      - name: Build Tags
        id: build-tags
        shell: bash
        run: |
          origin_tags=${{ inputs.tags }}
          tags=$(echo ${ origin_tags:-${{ steps.build-short-sha.outputs.short-sha }} } | sed 's#.*#${{ env.REGISTRY }}/${{ inputs.ecr-name }}:&#')
          echo "tags=$tags" >> $GITHUB_OUTPUT
      - name: Build Docker Args
        id: build-docker-build-args
        run: |
          docker_build_args=$(echo '${{ secrets.build-args }}' | sed '/^$/d' | sed 's/<<short-sha>>/${{ steps.build-short-sha.outputs.short-sha }}/g')
          echo "build-args=$docker_build_args" >> $GITHUB_OUTPUT
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ${{ steps.build-docker-build-args.outputs.build-args }}
          push: true
          tags: ${{ steps.build-tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
