on:
  workflow_call:
    secrets:
      build-args:
        required: false

    inputs:
      build-args:
        required: false
        type: string
        default: ''
      aws-account:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      environment-name:
        required: false
        type: string
        default: ''
      gha-role-name:
        required: false
        type: string
        default: 'gha-ecr'
      registry:
        required: true
        type: string
      repository:
        required: true
        type: string
      tags:
        required: false
        type: string
        default: '<<short-sha>>'
      platform:
        required: false
        type: string
        default: 'linux/amd64'
      run-on:
        required: false
        type: string
        default: "['ubuntu-latest']"

    outputs:
      image-tag:
        description: "Main Docker Image tag name"
        value: ${{ jobs.docker-build.outputs.image-tag }}
      registry:
        description: "Container Registry (ECR)"
        value: ${{ jobs.docker-build.outputs.registry }}
      repository:
        description: "Docker Image Repository"
        value: ${{ jobs.docker-build.outputs.repository }}
      short-sha:
        description: "Git commit short sha"
        value: ${{ jobs.docker-build.outputs.short-sha }}

jobs:
  docker-build:
    name: Docker Build
    runs-on: ${{ fromJson(inputs.run-on) }}
    outputs:
      registry: ${{ inputs.registry }}
      repository: ${{ inputs.repository }}
      image-tag: ${{ steps.build-tags.outputs.image-tag }}
      short-sha: ${{ steps.build-short-sha.outputs.short-sha }}
    environment:
      name: ${{ inputs.environment-name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build git commit short sha
        id: build-short-sha
        run: echo "short-sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/${{ inputs.gha-role-name }}
          aws-region: ${{ inputs.aws-region }}
          mask-aws-account-id: 'no'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Tags
        id: build-tags
        run: |
          tags=$(echo '${{ inputs.tags }}' | awk '{$1=$1};1' | sed '/^$/d' | sed 's/<<short-sha>>/${{ steps.build-short-sha.outputs.short-sha }}/' | sed '$!N;s/\n/,/')
          image_tag=$(echo $tags | cut -d ',' -f1)
          ecr_tags=$(echo $tags  | sed 's#,#\n#g' | sed 's#.*#${{ inputs.registry }}/${{ inputs.repository }}:&#' | sed '$!N;s#\n#,#')
          echo "image-tag=$image_tag" >> $GITHUB_OUTPUT
          echo "ecr-tags=$ecr_tags" >> $GITHUB_OUTPUT
      - name: Build Docker Args
        id: build-docker-build-args
        run: |
          echo 'docker_build_args<<EOF' >> $GITHUB_ENV
          echo '${{ secrets.build-args }}' | sed '/^$/d' | sed 's/<<short-sha>>/${{ steps.build-short-sha.outputs.short-sha }}/g' >> $GITHUB_ENV
          echo '${{ inputs.build-args }}' | sed '/^$/d' | sed 's/<<short-sha>>/${{ steps.build-short-sha.outputs.short-sha }}/g' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ inputs.platform }}
          build-args: ${{ env.docker_build_args }}
          push: true
          tags: ${{ steps.build-tags.outputs.ecr-tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
