on:
  workflow_call:
    secrets:
      aws-access-key-id: 
        required: true
      aws-secret-access-key:
        required: true
      aws-account:
        required: true
      build-args:
        required: false

    inputs:
      tags:
        required: false
        type: string
        default: ''
      aws-region: 
        required: false
        type: string
        default: 'eu-north-1'
      ecr-name:
        required: true
        type: string
      env-name:
        required: false
        type: string
        default: ''
      env-url:
        required: false
        type: string
        default: ''

    outputs:
      image-tag:
        description: "Docker Image tag name"
        value: ${{ jobs.docker-build.outputs.image-tag }}
      image-repository:
        description: "Docker Image Repository"
        value: ${{ jobs.docker-build.outputs.image-repository }}

env:
  REGISTRY: ${{ secrets.aws-account }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      image-repository: ${{ env.REGISTRY }}
      image-tag: ${{ steps.build-tags.outputs.tags }}
    environment:
      name: ${{ inputs.env-name }}
      url: ${{ inputs.env-url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.aws-access-key-id }}
          password: ${{ secrets.aws-secret-access-key }}
      - name: Build Tags
        id: build-tags
        shell: bash
        run: |
          origin_tags=${{ inputs.tags }} 
          tags=$(echo ${origin_tags:-$(git rev-parse --short HEAD)} | sed 's#.*#${{ env.REGISTRY }}/${{ inputs.ecr-name }}:&#')
          echo "tags=$tags" >> $GITHUB_OUTPUT
      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: ${{ secrets.build-args }}
          push: true
          tags: ${{ steps.build-tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
