on:
  workflow_call:

    inputs:
      aws-account:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      environment-name:
        required: false
        type: string
        default: ''
      tag:
        required: true
        type: string
      tag-list:
        required: true
        type: string
      run-on:
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  docker-manifest:
    name: Docker Manifest
    runs-on: ${{ inputs.run-on }}
    environment:
      name: ${{ inputs.environment-name }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/${{ inputs.gha-role-name }}
          aws-region: ${{ inputs.aws-region }}
          mask-aws-account-id: 'no'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@0.4.1
        with:
          inputs: ${{ inputs.tag }}
          images: ${{ inputs.tag-list }}
          push: true
