name: Jira Release

on:
  workflow_call:
    inputs:
      release-type: 
        required: false
        type: string
        default: 'simple'
      bump-minor-pre-major:
        required: false
        type: boolean
        default: true
      bump-patch-for-minor-pre-major:
        required: false
        type: boolean
        default: true
      extra-files:
        required: false
        type: string
      jira-project-key:
        required: true
        type: string
      jira-sub-domain:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      jira-email:
        required: true
      jira-token:
        required: true

jobs:
  jira-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please Action
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: ${{ inputs.release-type }}
          bump-minor-pre-major: ${{ inputs.bump-minor-pre-major }}
          bump-patch-for-minor-pre-major: ${{ inputs.bump-patch-for-minor-pre-major }}

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0

      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.github_token }}@github.com/google-github-actions/release-please-action.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
      
      - name: Collect JIRA issue numbers since last release/tag
        id: collect-jira-issues
        if: ${{ steps.release.outputs.release_created }}
        run: |
          tickets=$(git log --pretty=oneline \
            $(git tag --sort=-committerdate -l  "*.*.*" | head -2 | tail -1 | grep . || git rev-list --max-parents=0 HEAD)..\
            $(git tag --sort=-committerdate -l  "*.*.*" | head -1 | grep . || echo HEAD) | \
            grep -oP "${{ inputs.jira-project-key }}-\d{1,}" | sort | uniq | sed 's/^\|$/"/g' | xargs -r | sed -e 's/ /,/g')
          echo "tickets=$tickets" >> $GITHUB_OUTPUT

      - uses: StalemateInc/jira-release-action@main
        if: ${{ steps.release.outputs.release_created }}
        with:
          email: ${{ secrets.jira-email }}
          api_token: ${{ secrets.jira-token }}
          release_name: ${{ steps.release.outputs.tag_name }}
          tickets: ${{ steps.collect-jira-issues.outputs.tickets }}
          subdomain: ${{ inputs.jira-sub-domain }}
          jira_project: ${{ inputs.jira-project-key }}
          create: true
          release: false
