name: Jira Release

on:
  workflow_call:
    inputs:
      project-key:
        required: true
        type: string
      sub-domain:
        required: true
        type: string
      release-name:
        required: true
        type: string
    secrets:
      email:
        required: true
      token:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Collect JIRA issue numbers since last release/tag
        id: collect-jira-issues
        run: |
          tickets=$(git log --pretty=oneline \
            $(git tag --sort=-committerdate -l  "*.*.*" | head -2 | tail -1 | grep . || git rev-list --max-parents=0 HEAD)..\
            $(git tag --sort=-committerdate -l  "*.*.*" | head -1 | grep . || echo HEAD) | \
            grep -oP "${{ inputs.project-key }}-\d{1,}" | sort | uniq | sed 's/^\|$/"/g' | xargs -r | sed -e 's/ /,/g')
          echo "tickets=$tickets" >> $GITHUB_OUTPUT

      - uses: StalemateInc/jira-release-action@main
        with:
          email: ${{ secrets.email }}
          api_token: ${{ secrets.token }}
          release_name: ${{ inputs.release-name }}
          tickets: ${{ steps.collect-jira-issues.outputs.tickets }}
          subdomain: ${{ inputs.sub-domain }}
          jira_project: ${{ inputs.project-key }}
          create: true
          release: false
