name: Release Please

on:
  workflow_call:
    inputs:
      release-type: 
        required: false
        type: string
        default: 'simple'
      bump-minor-pre-major:
        required: false
        type: boolean
        default: true
      bump-patch-for-minor-pre-major:
        required: false
        type: boolean
        default: true
      extra-files:
        required: false
        type: string
    outputs:
      release-created:
        description: "Indicates if GitHub release has been created by the action"
        value: ${{ jobs.release-please.outputs.release-created }}
    secrets:
      github-token:
        required: false

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Run Release Please Action
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: ${{ inputs.release-type }}
          bump-minor-pre-major: ${{ inputs.bump-minor-pre-major }}
          bump-patch-for-minor-pre-major: ${{ inputs.bump-patch-for-minor-pre-major }}
          extra-files: ${{ inputs.extra-files }}
          token: ${{ secrets.github-token || secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.github-token }}@github.com/google-github-actions/release-please-action.git"
          git tag -d v${{ steps.release.outputs.major }} || true
          git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :v${{ steps.release.outputs.major }} || true
          git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin v${{ steps.release.outputs.major }}
          git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
