name: Release Please

on:
  workflow_call:
    inputs:
      release-type: 
        required: false
        type: string
        default: 'simple'
      bump-minor-pre-major:
        required: false
        type: boolean
        default: false
      bump-patch-for-minor-pre-major:
        required: false
        type: boolean
        default: false
      extra-files:
        required: false
        type: string
    outputs:
      release-created:
        description: "Indicates if GitHub release has been created by the action"
        value: ${{ jobs.release-please.outputs.release-created }}
      tag-name:
        description: "Release tag name"
        value: ${{ jobs.release-please.outputs.tag-name}}
    secrets:
      github-token:
        required: false

jobs:
  release-please:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run Release Please Action
        uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: ${{ inputs.release-type }}
          bump-minor-pre-major: ${{ inputs.bump-minor-pre-major }}
          bump-patch-for-minor-pre-major: ${{ inputs.bump-patch-for-minor-pre-major }}
          extra-files: ${{ inputs.extra-files }}
          token: ${{ (secrets.github-token == '' && secrets.GITHUB_TOKEN) || secrets.github-token }}

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
